apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-umkr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-umkr@sha256:075723d5189d8efef93d5c070f0fdd5f12a4ce0c9eb06e2ed3796996cf91ab06
        name: my-nodejs
        resources: {}
status: {}
